name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-ci:
    runs-on: ubuntu-22.04
    # env:   # 작업 디렉터리가 최상위 경로가 아닌 경우에 다음과 같이 환경변수로 지정해줄 수 있다
    #   working-directory: Second Seminar/SecondSeminar

    steps: 
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: application.yaml 생성
      run: | 
          cd src/main/resources
          echo "${{ secrets.APPLICATION }}" > ./application-deploy.yaml
      working-directory: ${{ env.working-directory }}

    - name: 빌드
      run: |
          chmod +x gradlew
          ./gradlew build -x test
      working-directory: ${{ env.working-directory }}
      shell: bash

######## 여기까지는 CI.yml와 동일 #########

    - name: docker build 가능하도록 환경 설정
      uses: docker/setup-buildx-action@v2.9.1
      
    - name: docker hub에로그인
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
        password: ${{ secrets.DOCKERHUB_LOGIN_ACCESSTOKEN }}

    - name: docker image 빌드 및 푸시
      run: |
        docker build --platform linux/amd64 -t yejunpark1/do-sopt-seminar .
        docker push yejunpark1/do-sopt-seminar
      # working-directory: ${{ env.working-directory }}

  deploy-cd:      
    needs: deploy-ci
    runs-on: ubuntu-22.04

    steps:    # EC2 인스턴스 내부에서 도커 이미지 다운로드
    - name: 도커 컨테이너 실행
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RELEASE_SERVER_IP }}
        username: ${{ secrets.RELEASE_SERVER_USER }}
        key: ${{ secrets.RELEASE_SERVER_KEY }}
        # *-p : Port {외부에서 접속할 포트}:ㅖ내부에서 실행되는 포트}로 지정
        script: |
					docker rm -f do-sopt-seminar
					docker image pull yejunpark1/do-sopt-seminar
          docker run -d --name do-sopt-seminar-8080 -p 8080:8080 yejunpark1/do-sopt-seminar
